services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  airflow:
    image: apache/airflow:2.9.2
    env_file: 
      - ../config/.env
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../docker/airflow/requirements.txt:/requirements.txt
      - airflow-home:/opt/airflow           # <-- persist Airflow home (SQLite lives here)
    command: >
      bash -c "
      python -V &&
      pip install --no-cache-dir -r /requirements.txt &&
      airflow standalone
      "

  kafka-producer:
    build: ../kafka/producer
    env_file: ../config/.env
    depends_on:
      - kafka
    command: python produce_events.py

volumes:
  airflow-home:
